# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3843df83cc13792a061269525f617fae0ee1be6a47f952f8ce3f2517fe2c512fcaaea25baca277c4f4cb5f32de417d3fc91ccaa0d2103bf92f5a8de9bfc71960

test:
  secret_key_base: 16e1a86063074d44335fa48df7133e2e9741ea7a1f98bc39a1886da17da2a22493b021e674c9f92b8aa89b10272fa3df435095b75e0e2a45ba667b55f24c5974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
